### PR TITLE
Fix bug to allow demographic information to be shown in clinc module.

### PR DESCRIPTION
**Pull request by Adilatec**
From the bug given to group 21 in the following link https://github.com/udsm-dhis2-lab/iCareConnect/issues/243
Registration number:2021-04-04669, Adila Lambi 
 where I was dealing with demographic information of patients in clinic module to be shown and not hidden.
I correct the bug by updating styles.css were I increased padding from 6px to 19px as padding improve the readability and organization of your code. It enhances visual clarity, making it easier to distinguish between different sections and elements.

### CODE REVIEW

**Comment by Adilatec** [comment]
Groupb21 bug fix by updating styles.css file

**Comment by Adilatec** [comment]
New commit from abdulsalaam mahyoro, registration number 2021-04-05403 on changes in field component.scss file for issue in group 21 of the following link https://github.com/udsm-dhis2-lab/iCareConnect/issues/243

**Comment by abdulsalaam11** [comment]
abdulsalaam mahyoro, registration number 2021-04-05403, i have commit on changes in field component.scss file for issue in group 21 of the following link https://github.com/udsm-dhis2-lab/iCareConnect/issues/243, to help solve drop list bug from diagnosis.

**Comment by Rose5252** [comment]
From group 21 with the following bug link ,https://github.com/udsm-dhis2-lab/iCareConnect/issues/243
Registration number:2021-04-01727, Rose John Enos where together with other members i manage to participate in solving visibility problem of drop list in diagnosis by add height element to fit content so as to improve better readerbility

**Comment by reycos111** [comment]
Rehema B. Kanokoleke with Reg.No 2019-04-03560, with my Group Mate (Group21) we collaborated to fix Issues of Visibility and Readability on drop down menu items by updating style file (style.css) in the issue #243

**Comment by Ramadhani202208** [comment]
seen

**Pull request closed without merging**
