### PR TITLE
fix issue 248 , where I changed the path where were used to resemble …

### PR DESCRIPTION
**Pull request by Twalibu-code**
…with my local path which looks like this after change /assignment/software/icareconnect/ui/src/app/shared/resources/openmrs within patient-history.component.ts file

### CODE REVIEW

**Comment by Twalibu-code** [comment]
what I changed is the directories/ path that where not found when I type npm start to resemble to my local path and delete outDir to other file.
our issue link is https://github.com/udsm-dhis2-lab/iCareConnect/issues/248
************************************************************************************************************
NAME: PEMBE, TWALIBU A
REG NO: 2020-04-10359

**Comment by Twalibu-code** [comment]
you as a lecturer you should prepare clean and easy to understand documents for the task you provide us.
TAHNK YOU

**Comment by Jerydavid** [comment]
NAME: NADEIT, JEREMIA D
REG NO: 2021-04-09281

**Comment by janeth-01** [comment]
NAME: JANETH JUSTINE MKINI
REG:2021-04-07261

**Comment by Twalibu-code** [comment]
dj

**Comment by Phillyshine01** [comment]
…with my local path which looks like this after change /assignment/software/icareconnect/ui/src/app/shared/resources/openmrs within patient-history.component.ts file

what I changed is the directories/ path that where not found when I type npm start to resemble to my local path and delete outDir to other file.
our issue link is https://github.com/udsm-dhis2-lab/iCareConnect/issues/248

Name : SHINE PHILIPINA FELICHISM
REGNO: 2021-04-11635

**Pull request closed without merging**
